/* WARNING! All changes made to this file will be lost! */

#ifndef W_SRC_NDN_CXX_CONFIG_HPP_WAF
#define W_SRC_NDN_CXX_CONFIG_HPP_WAF

#define NDN_CXX_HAVE_IS_DEFAULT_CONSTRUCTIBLE 1
#define NDN_CXX_HAVE_IS_MOVE_CONSTRUCTIBLE 1
#define NDN_CXX_HAVE_IS_MOVE_ASSIGNABLE 1
#define NDN_CXX_HAVE_CXX_FRIEND_TYPENAME 1
#define NDN_CXX_HAVE_CXX_OVERRIDE_FINAL 1
#define NDN_CXX_HAVE_PTHREAD 1
#define NDN_CXX_HAVE_RT 1
#define NDN_CXX_HAVE_GETPASS 1
#define NDN_CXX_HAVE_RTNETLINK 1
#define NDN_CXX_HAVE_SQLITE3 1
#define NDN_CXX_HAVE_CRYPTOPP_CONFIG_H 1
#define NDN_CXX_SYSCONFDIR "/opt/ndn/sysroots/i586-poky-linux-uclibc/usr/etc"

#endif /* W_SRC_NDN_CXX_CONFIG_HPP_WAF */
