/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/schwannden/ndn/Galileo-Runtime/meta-clanton_v1.0.1/yocto_build/tmp/sysroots/x86_64-linux/usr/bin/perl-native/perl5.14.3.real bin/enc2xs -Q -O -o def_t.c -f def_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t ascii_encoding;
extern encode_t ascii_ctrl_encoding;
extern encode_t iso_8859_1_encoding;
extern encode_t null_encoding;
