/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/schwannden/ndn/Galileo-Runtime/meta-clanton_v1.0.1/yocto_build/tmp/sysroots/x86_64-linux/usr/bin/perl-native/perl5.14.3.real ../bin/enc2xs -Q -o ma_03_t.c -f ma_03_t.fnm
 enc2xs VERSION 2.07
*/
extern encode_t MacChineseTrad_encoding;
